function J_sym = JacobianPickAndPlace(in1,in2)
%JacobianPickAndPlace
%    J_sym = JacobianPickAndPlace(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Oct-2025 10:36:02

%UR3e Pick And Place Jacobian
L2 = in2(2,:);
L3 = in2(3,:);
L4 = in2(4,:);
L5 = in2(5,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = theta2+theta3;
t7 = cos(t6);
t8 = sin(t6);
t9 = L3.*t7;
t10 = L3.*t2.*t8;
t11 = L3.*t4.*t8;
t12 = -t9;
J_sym = reshape([L4.*t2+L5.*t4+t4.*t9+L2.*t3.*t4,-L5.*t2+L4.*t4+t2.*t12-L2.*t2.*t3,0.0,1.0,t10+L2.*t2.*t5,t11+L2.*t4.*t5,t12-L2.*t3,0.0,t10,t11,t12,0.0,0.0,0.0,0.0,-1.0],[4,4]);
end
